"""DXCC country name → ISO-3166-1 alpha-2 code.

Not exhaustive — the cty.dat file contains ~340 DXCC entities, many of
which are special status (research stations, disputed, extinct) without
a mainstream ISO code. This table covers the most-worked ~130 entities
that account for the vast majority of spots. Missing entries fall back
to no flag — the callsign still renders, just without the country
emblem.
"""
from __future__ import annotations

COUNTRY_TO_ISO: dict[str, str] = {
    # Top activity
    "United States of America": "US",
    "United States": "US",
    "Canada": "CA",
    "Mexico": "MX",
    "Argentina": "AR",
    "Brazil": "BR",
    "Chile": "CL",
    "Colombia": "CO",
    "Peru": "PE",
    "Venezuela": "VE",
    "Uruguay": "UY",
    "Paraguay": "PY",
    "Ecuador": "EC",
    "Bolivia": "BO",
    "Cuba": "CU",
    "Dominican Republic": "DO",
    "Puerto Rico": "PR",
    "Jamaica": "JM",
    "Haiti": "HT",
    "Bahamas": "BS",
    "Barbados": "BB",
    "Trinidad & Tobago": "TT",
    "Guatemala": "GT",
    "Honduras": "HN",
    "Nicaragua": "NI",
    "El Salvador": "SV",
    "Costa Rica": "CR",
    "Panama": "PA",
    "Belize": "BZ",
    # Europe
    "England": "GB",
    "Scotland": "GB",
    "Wales": "GB",
    "Northern Ireland": "GB",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Jersey": "JE",
    "Guernsey": "GG",
    "France": "FR",
    "Germany": "DE",
    "Fed. Rep. of Germany": "DE",
    "Italy": "IT",
    "Spain": "ES",
    "Portugal": "PT",
    "Netherlands": "NL",
    "Belgium": "BE",
    "Luxembourg": "LU",
    "Switzerland": "CH",
    "Austria": "AT",
    "Liechtenstein": "LI",
    "Denmark": "DK",
    "Sweden": "SE",
    "Norway": "NO",
    "Finland": "FI",
    "Iceland": "IS",
    "Poland": "PL",
    "Czech Republic": "CZ",
    "Slovak Republic": "SK",
    "Hungary": "HU",
    "Romania": "RO",
    "Bulgaria": "BG",
    "Greece": "GR",
    "Turkey": "TR",
    "Cyprus": "CY",
    "Malta": "MT",
    "Monaco": "MC",
    "San Marino": "SM",
    "Vatican": "VA",
    "Andorra": "AD",
    "Croatia": "HR",
    "Slovenia": "SI",
    "Serbia": "RS",
    "Bosnia-Herzegovina": "BA",
    "North Macedonia": "MK",
    "Macedonia": "MK",
    "Albania": "AL",
    "Kosovo": "XK",
    "Montenegro": "ME",
    "Moldova": "MD",
    "Ukraine": "UA",
    "Belarus": "BY",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Estonia": "EE",
    "European Russia": "RU",
    "Asiatic Russia": "RU",
    "Kaliningrad": "RU",
    # Asia / Oceania
    "Japan": "JP",
    "China": "CN",
    "South Korea": "KR",
    "Republic of Korea": "KR",
    "North Korea": "KP",
    "DPR of Korea": "KP",
    "Taiwan": "TW",
    "Hong Kong": "HK",
    "Macao": "MO",
    "Macau": "MO",
    "Philippines": "PH",
    "Vietnam": "VN",
    "Thailand": "TH",
    "Malaysia": "MY",
    "West Malaysia": "MY",
    "East Malaysia": "MY",
    "Singapore": "SG",
    "Indonesia": "ID",
    "Brunei Darussalam": "BN",
    "Cambodia": "KH",
    "Laos": "LA",
    "Myanmar": "MM",
    "India": "IN",
    "Pakistan": "PK",
    "Bangladesh": "BD",
    "Sri Lanka": "LK",
    "Nepal": "NP",
    "Bhutan": "BT",
    "Maldives": "MV",
    "Afghanistan": "AF",
    "Iran": "IR",
    "Iraq": "IQ",
    "Israel": "IL",
    "Palestine": "PS",
    "Jordan": "JO",
    "Lebanon": "LB",
    "Syria": "SY",
    "Saudi Arabia": "SA",
    "Kuwait": "KW",
    "Bahrain": "BH",
    "Qatar": "QA",
    "United Arab Emirates": "AE",
    "Oman": "OM",
    "Yemen": "YE",
    "Kazakhstan": "KZ",
    "Uzbekistan": "UZ",
    "Turkmenistan": "TM",
    "Kyrgyzstan": "KG",
    "Tajikistan": "TJ",
    "Armenia": "AM",
    "Azerbaijan": "AZ",
    "Georgia": "GE",
    "Mongolia": "MN",
    # Oceania
    "Australia": "AU",
    "New Zealand": "NZ",
    "Papua New Guinea": "PG",
    "Fiji": "FJ",
    "Solomon Islands": "SB",
    "Vanuatu": "VU",
    "Samoa": "WS",
    "Tonga": "TO",
    "Kiribati": "KI",
    "Tuvalu": "TV",
    "Marshall Islands": "MH",
    "Micronesia": "FM",
    "Palau": "PW",
    "Nauru": "NR",
    "French Polynesia": "PF",
    "New Caledonia": "NC",
    "Wallis & Futuna": "WF",
    "Cook Islands": "CK",
    "Niue": "NU",
    # Africa
    "South Africa": "ZA",
    "Morocco": "MA",
    "Algeria": "DZ",
    "Tunisia": "TN",
    "Libya": "LY",
    "Egypt": "EG",
    "Sudan": "SD",
    "South Sudan": "SS",
    "Ethiopia": "ET",
    "Eritrea": "ER",
    "Somalia": "SO",
    "Djibouti": "DJ",
    "Kenya": "KE",
    "Uganda": "UG",
    "Tanzania": "TZ",
    "Rwanda": "RW",
    "Burundi": "BI",
    "Mozambique": "MZ",
    "Madagascar": "MG",
    "Mauritius": "MU",
    "Seychelles": "SC",
    "Comoros": "KM",
    "Reunion Island": "RE",
    "Mayotte": "YT",
    "Malawi": "MW",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
    "Botswana": "BW",
    "Namibia": "NA",
    "Angola": "AO",
    "Democratic Rep. of Congo": "CD",
    "Congo": "CG",
    "Gabon": "GA",
    "Cameroon": "CM",
    "Nigeria": "NG",
    "Benin": "BJ",
    "Togo": "TG",
    "Ghana": "GH",
    "Ivory Coast": "CI",
    "Liberia": "LR",
    "Sierra Leone": "SL",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Senegal": "SN",
    "Gambia": "GM",
    "Mali": "ML",
    "Burkina Faso": "BF",
    "Niger": "NE",
    "Chad": "TD",
    "Central African Republic": "CF",
    "Mauritania": "MR",
    "Cape Verde": "CV",
    "Sao Tome & Principe": "ST",
    "Equatorial Guinea": "GQ",
    # Remaining notable
    "Greenland": "GL",
    "Faroe Islands": "FO",
    "Svalbard": "SJ",
    "Gibraltar": "GI",
    "Bermuda": "BM",
    "Cayman Islands": "KY",
    "Turks & Caicos Islands": "TC",
    "British Virgin Islands": "VG",
    "US Virgin Islands": "VI",
    "Anguilla": "AI",
    "Aruba": "AW",
    "Curacao": "CW",
    "St. Maarten": "SX",
    "Saba & St. Eustatius": "BQ",
    "Bonaire": "BQ",
    "Guadeloupe": "GP",
    "Martinique": "MQ",
    "St. Barthelemy": "BL",
    "Dominica": "DM",
    "Grenada": "GD",
    "St. Lucia": "LC",
    "St. Vincent": "VC",
    "Montserrat": "MS",
    "Falkland Islands": "FK",
    "French Guiana": "GF",
    "Guyana": "GY",
    "Suriname": "SR",
    "Hawaii": "US",
    "Alaska": "US",
}


def country_to_iso(name: str) -> str:
    """Look up ISO-3166 alpha-2 code. Returns '' if unknown."""
    return COUNTRY_TO_ISO.get(name.strip(), "")


def iso_to_flag(iso2: str) -> str:
    """Regional-indicator flag emoji for an ISO-3166 alpha-2 code.

    Note: Windows's default emoji font doesn't render regional-indicator
    pairs as flag pictures — it shows the two letters in boxes. On macOS
    and Linux with Noto Color Emoji, they render as proper flags. Either
    way, the glyphs provide country context.
    """
    iso2 = iso2.upper().strip()
    if len(iso2) != 2 or not iso2.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in iso2)
